service: nerdwork-backend

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    DATABASE_URL: ${ssm:/nerdwork/${self:provider.stage}/database-url}
    JWT_SECRET: ${ssm:/nerdwork/${self:provider.stage}/jwt-secret}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true
  exclude:
    - node_modules/**
    - .git/**
    - .github/**
    - _tests_/**