service: nerdwork-file

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    DATABASE_URL: ${ssm:/nerdwork/${self:provider.stage}/database-url}
    JWT_SECRET: ${ssm:/nerdwork/${self:provider.stage}/jwt-secret}
    AWS_REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource:
            - arn:aws:ssm:${self:provider.region}:*:parameter/nerdwork/${self:provider.stage}/*

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi:
          path: /file
          method: any
      - httpApi:
          path: /file/{proxy+}
          method: any

plugins:
  - serverless-offline



